/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param text 
 * @param listId 
 * @param checked 
 * @param createdAt 
 */


data class ToDoItem (

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "text")
    val text: kotlin.String? = null,

    @Json(name = "listId")
    val listId: java.util.UUID? = null,

    @Json(name = "checked")
    val checked: kotlin.Boolean? = null,

    @Json(name = "createdAt")
    val createdAt: kotlin.String? = null

)

